### ISSUE TITLE
Can't import Pytest 

### ISSUE THREAD

**Issue by SPH73** [feldroy/django-crash-course-live-class-001#13]
When trying to import pytest in test_models.py I am getting this problem:

![image](https://user-images.githubusercontent.com/48051095/87827771-72245780-c873-11ea-8ce9-c020ad13344e.png)

**Comment by luzfcb** [comment]
I see the error now.

The problem is that your VSCode is not configured to use the "everycheese" conda environment


1 - On your project inside the VSCode, click into a python file, like the manager.py

Note: I found out that VSCode only enables Python support if a python file is open.

2 - Select your `everycheese` conda environment by following the steps on 

https://code.visualstudio.com/docs/python/environments

**Comment by luzfcb** [comment]
@SPH73 As you use `pipenv`, check if this can help to solve the problem https://www.benjaminpack.com/blog/vs-code-python-pipenv/

**Comment by SPH73** [comment]
Thanks Fabio, I'll give it a try

**Comment by SPH73** [comment]
Here I was able load the interpreter and import pytest but when I tried to run the test I got this error

![image](https://user-images.githubusercontent.com/48051095/87829649-5d49c300-c877-11ea-982c-7d7394eeeace.png)

**Comment by SPH73** [comment]
I am in the wrong directory, sorry!

**Comment by SPH73** [comment]
But it still fails in the correct one
